"""Statistics engine (L5) — the heart of the project.

No number leaves this layer without its uncertainty, and no gate-critical formula is a black
box: Wilson, McNemar, BH-FDR, the pass^k estimators, and the power curves are implemented here
with their sources cited, and validated by Monte-Carlo simulation in ``tests/simulation/``.
"""

from agentgate.stats.aggregate import (
    latency_percentiles,
    repetition_scores,
    summarise_metric,
    summarise_run,
    task_means,
)
from agentgate.stats.compare import ComparisonConfig, build_paired_data, compare_all, compare_metric
from agentgate.stats.intervals import (
    DEFAULT_BOOTSTRAP,
    DEFAULT_LEVEL,
    bootstrap_bca,
    clip_estimate,
    clt_interval,
    clustered_interval,
    percentile_interval,
    quantile,
    se_inflation,
    wilson_interval,
    z_for,
)
from agentgate.stats.multiplicity import (
    Adjustment,
    benjamini_hochberg,
    bonferroni,
    expected_false_alarms,
    family_wise_error,
)
from agentgate.stats.paired import (
    PairedData,
    choose_test,
    cohens_dz,
    difference_estimate,
    disagreement,
    discordant_counts,
    mcnemar_exact,
    mcnemar_odds_ratio,
    paired_correlation,
    paired_t_test,
    permutation_test,
    run_paired_test,
    wilcoxon_test,
)
from agentgate.stats.power import (
    PowerInputs,
    describe,
    mcnemar_power,
    minimum_detectable_effect,
    paired_power,
    plan_suite_size,
    power_report,
    required_pairs,
)
from agentgate.stats.reliability import (
    TaskOutcomes,
    flake_rate,
    naive_pass_hat_k,
    outcomes_from_scores,
    pass_at_k,
    pass_hat_k,
    pass_hat_k_series,
    reliability_report,
    score_variance,
)
from agentgate.stats.variance import (
    budget_advice,
    decompose,
    inflate_estimate,
    judge_variance_share,
    propagate_judge_variance,
)

__all__ = [
    "DEFAULT_BOOTSTRAP",
    "DEFAULT_LEVEL",
    "Adjustment",
    "ComparisonConfig",
    "PairedData",
    "PowerInputs",
    "TaskOutcomes",
    "benjamini_hochberg",
    "bonferroni",
    "bootstrap_bca",
    "budget_advice",
    "build_paired_data",
    "choose_test",
    "clip_estimate",
    "clt_interval",
    "clustered_interval",
    "cohens_dz",
    "compare_all",
    "compare_metric",
    "decompose",
    "describe",
    "difference_estimate",
    "disagreement",
    "discordant_counts",
    "expected_false_alarms",
    "family_wise_error",
    "flake_rate",
    "inflate_estimate",
    "judge_variance_share",
    "latency_percentiles",
    "mcnemar_exact",
    "mcnemar_odds_ratio",
    "mcnemar_power",
    "minimum_detectable_effect",
    "naive_pass_hat_k",
    "outcomes_from_scores",
    "paired_correlation",
    "paired_power",
    "paired_t_test",
    "pass_at_k",
    "pass_hat_k",
    "pass_hat_k_series",
    "percentile_interval",
    "permutation_test",
    "plan_suite_size",
    "power_report",
    "propagate_judge_variance",
    "quantile",
    "reliability_report",
    "repetition_scores",
    "required_pairs",
    "run_paired_test",
    "score_variance",
    "se_inflation",
    "summarise_metric",
    "summarise_run",
    "task_means",
    "wilcoxon_test",
    "wilson_interval",
    "z_for",
]
