"""A synthetic internal wiki and its loader (F1.2).

The RAG reference agent needs a corpus that is small, offline, deterministic, and *fact-bearing*
— every document states values a question can have exactly one correct answer to, which is what
makes reference answers and gold contexts authorable without hand-labelling.

The generator is committed alongside its output so the corpus can be regenerated byte-identically
(A3.4) and so a reader can see there is no hidden magic in the RAG numbers.
"""

from __future__ import annotations

import random
import re
from collections.abc import Iterator
from dataclasses import dataclass
from pathlib import Path
from typing import Final

CORPUS_SEED: Final = 20260101
DEFAULT_CORPUS_DIR: Final = Path("datasets/corpus/wiki")

COMPANY: Final = "Northwind Robotics"

TOPICS: Final[dict[str, tuple[str, ...]]] = {
    "onboarding": (
        "laptop-provisioning",
        "buddy-program",
        "first-week-checklist",
        "badge-access",
        "payroll-setup",
        "training-modules",
        "team-introductions",
        "workspace-setup",
        "email-groups",
        "probation-review",
    ),
    "security": (
        "password-policy",
        "mfa-enrollment",
        "phishing-reporting",
        "device-encryption",
        "vpn-access",
        "secrets-management",
        "vulnerability-triage",
        "access-reviews",
        "physical-security",
        "incident-classification",
    ),
    "deployment": (
        "release-trains",
        "canary-rollout",
        "rollback-procedure",
        "feature-flags",
        "database-migrations",
        "artifact-signing",
        "staging-parity",
        "blue-green",
        "deploy-freeze",
        "post-deploy-checks",
    ),
    "incident-response": (
        "severity-levels",
        "paging-rotation",
        "war-room-protocol",
        "status-page",
        "postmortem-template",
        "customer-comms",
        "escalation-ladder",
        "on-call-handoff",
        "runbook-index",
        "incident-metrics",
    ),
    "procurement": (
        "vendor-onboarding",
        "purchase-approval",
        "software-licensing",
        "hardware-refresh",
        "contract-review",
        "invoice-processing",
        "supplier-audits",
        "budget-codes",
        "renewal-calendar",
        "asset-tagging",
    ),
    "travel": (
        "booking-policy",
        "expense-limits",
        "visa-support",
        "conference-attendance",
        "mileage-reimbursement",
        "hotel-tiers",
        "travel-insurance",
        "per-diem",
        "international-travel",
        "trip-reports",
    ),
    "benefits": (
        "health-coverage",
        "parental-leave",
        "learning-stipend",
        "retirement-matching",
        "wellness-program",
        "equipment-allowance",
        "sabbatical-policy",
        "volunteer-days",
        "commuter-benefits",
        "referral-bonus",
    ),
    "data-retention": (
        "log-retention",
        "backup-schedule",
        "customer-data-deletion",
        "audit-trails",
        "archival-tiers",
        "pii-classification",
        "export-requests",
        "legal-hold",
        "anonymization",
        "retention-exceptions",
    ),
    "api-guidelines": (
        "versioning",
        "rate-limits",
        "error-format",
        "pagination",
        "authentication",
        "idempotency",
        "deprecation-policy",
        "webhooks",
        "sdk-support",
        "changelog-standards",
    ),
    "release-process": (
        "branch-strategy",
        "code-review",
        "changelog-entries",
        "version-bumps",
        "release-notes",
        "qa-signoff",
        "beta-program",
        "hotfix-path",
        "dependency-updates",
        "release-metrics",
    ),
    "support-tiers": (
        "bronze-tier",
        "silver-tier",
        "gold-tier",
        "response-targets",
        "escalation-paths",
        "coverage-hours",
        "dedicated-engineers",
        "quarterly-reviews",
        "credit-policy",
        "renewal-terms",
    ),
    "hardware": (
        "workstation-specs",
        "robot-arm-models",
        "sensor-calibration",
        "spare-parts",
        "firmware-updates",
        "safety-interlocks",
        "lab-access",
        "maintenance-windows",
        "component-lifespan",
        "shipping-crates",
    ),
}

_TEAMS: Final = (
    "Platform",
    "Security",
    "People Ops",
    "Field Engineering",
    "Finance",
    "Reliability",
)
_ROLES: Final = (
    "the Platform lead",
    "the Security officer",
    "the People Ops partner",
    "the Field Engineering manager",
    "the Finance controller",
    "the on-call SRE",
)
_METRICS: Final = (
    ("service level target", "%", (95, 100)),
    ("turnaround time", " business days", (1, 10)),
    ("retention window", " days", (30, 365)),
    ("approval threshold", " USD", (100, 5000)),
    ("review cadence", " weeks", (2, 26)),
)


@dataclass(frozen=True, slots=True)
class WikiDoc:
    """One corpus document."""

    doc_id: str
    topic: str
    title: str
    text: str

    @property
    def path_name(self) -> str:
        """Filename this document is stored under."""
        return f"{self.doc_id}.md"


@dataclass(frozen=True, slots=True)
class DocFact:
    """A single answerable fact stated by a document — the seed of a QA task."""

    doc_id: str
    question: str
    answer: str


def _title_case(slug: str) -> str:
    return " ".join(word.capitalize() for word in slug.split("-"))


def generate_corpus(seed: int = CORPUS_SEED) -> tuple[list[WikiDoc], list[DocFact]]:
    """Generate the wiki deterministically.

    Args:
        seed: RNG seed. The committed corpus uses :data:`CORPUS_SEED`.

    Returns:
        ``(documents, facts)`` where each fact has exactly one supporting document.
    """
    rng = random.Random(seed)
    docs: list[WikiDoc] = []
    facts: list[DocFact] = []
    for topic, subareas in TOPICS.items():
        for subarea in subareas:
            doc_id = f"{topic}--{subarea}"
            title = f"{_title_case(topic)}: {_title_case(subarea)}"
            metric_name, unit, (low, high) = _METRICS[rng.randrange(len(_METRICS))]
            value = rng.randrange(low, high + 1)
            owner = _ROLES[rng.randrange(len(_ROLES))]
            team = _TEAMS[rng.randrange(len(_TEAMS))]
            days = rng.randrange(1, 15)
            text = (
                f"# {title}\n\n"
                f"## Summary\n"
                f"This page describes how {COMPANY} handles {_title_case(subarea).lower()} "
                f"within {_title_case(topic).lower()}.\n\n"
                f"## Key facts\n"
                f"- The {metric_name} for {_title_case(subarea).lower()} is {value}{unit}.\n"
                f"- {owner.capitalize()} owns this process.\n"
                f"- Requests are processed within {days} business days.\n\n"
                f"## Escalation\n"
                f"Contact the {team} team if the process stalls for more than "
                f"{days * 2} business days.\n"
            )
            docs.append(WikiDoc(doc_id=doc_id, topic=topic, title=title, text=text))
            facts.append(
                DocFact(
                    doc_id=doc_id,
                    question=(
                        f"What is the {metric_name} for {_title_case(subarea).lower()} "
                        f"in {_title_case(topic).lower()}?"
                    ),
                    answer=f"{value}{unit}",
                )
            )
            facts.append(
                DocFact(
                    doc_id=doc_id,
                    question=f"Which team handles escalations for {_title_case(subarea).lower()}?",
                    answer=f"the {team} team",
                )
            )
    return docs, facts


def write_corpus(target_dir: str | Path = DEFAULT_CORPUS_DIR, *, seed: int = CORPUS_SEED) -> int:
    """Write the generated corpus to disk.

    Args:
        target_dir: Destination directory, created if missing.
        seed: Generator seed.

    Returns:
        Number of documents written.
    """
    target = Path(target_dir)
    target.mkdir(parents=True, exist_ok=True)
    docs, _ = generate_corpus(seed)
    for doc in docs:
        (target / doc.path_name).write_text(doc.text, encoding="utf-8")
    return len(docs)


class WikiCorpus:
    """An in-memory corpus loaded from disk or generated on the fly.

    Args:
        docs: Documents to serve. Defaults to the generated corpus, so tests and the demo work
            without a checkout of ``datasets/``.
    """

    def __init__(self, docs: list[WikiDoc] | None = None) -> None:
        self._docs = docs if docs is not None else generate_corpus()[0]
        self._by_id = {doc.doc_id: doc for doc in self._docs}

    @classmethod
    def load(cls, directory: str | Path = DEFAULT_CORPUS_DIR) -> WikiCorpus:
        """Load markdown documents from ``directory``, falling back to generation."""
        path = Path(directory)
        if not path.is_dir():
            return cls()
        docs = [
            WikiDoc(
                doc_id=file.stem,
                topic=file.stem.split("--", 1)[0],
                title=_first_heading(text := file.read_text(encoding="utf-8")),
                text=text,
            )
            for file in sorted(path.glob("*.md"))
        ]
        return cls(docs) if docs else cls()

    def __len__(self) -> int:
        """Number of documents."""
        return len(self._docs)

    def __iter__(self) -> Iterator[WikiDoc]:
        """Iterate documents in id order."""
        return iter(self._docs)

    @property
    def docs(self) -> list[WikiDoc]:
        """All documents, in id order."""
        return list(self._docs)

    def get(self, doc_id: str) -> WikiDoc | None:
        """Return the document with ``doc_id``, or ``None``."""
        return self._by_id.get(doc_id)


def _first_heading(text: str) -> str:
    match = re.search(r"^#\s+(.+)$", text, flags=re.MULTILINE)
    return match.group(1).strip() if match else ""
