"""Generate ``docs/metrics.md`` from the registry.

Metric documentation is derived from the code, never maintained beside it. A metric catalogue
that has drifted from its implementation is worse than none: it makes a reader confident about
a number that means something else.
"""

from __future__ import annotations

import inspect
from pathlib import Path

from agentgate.metrics import registry
from agentgate.metrics.base import Metric
from agentgate.schemas.common import MetricFamily

FAMILY_INTROS: dict[MetricFamily, str] = {
    MetricFamily.OUTCOME: (
        "Did the task get done? `outcome.task_success` runs the task's programmatic checker "
        "against sandbox end state where one exists; the string metrics measure phrasing "
        "agreement, which is a different question."
    ),
    MetricFamily.TRAJECTORY: (
        "How the answer was reached. Every dimension is its own metric — a blended trajectory "
        "score lets a collapse in tool selection hide behind good argument accuracy."
    ),
    MetricFamily.RAG: (
        "Retrieval-augmented behaviour. Native implementations, RAGAS-comparable; divergences "
        "are documented rather than smoothed over."
    ),
    MetricFamily.SAFETY: (
        "Tripwires. All binary, all lower-is-better, and all able to fail the gate on their own "
        "with no hypothesis test in the way (C3)."
    ),
    MetricFamily.EFFICIENCY: ("What the run cost in time, tokens, calls, and projected dollars."),
    MetricFamily.RELIABILITY: (
        "Computed by the statistics engine from K repetitions rather than from a single sample: "
        "pass@k, pass^k, flake rate, and score variance."
    ),
}

_HEADER = """<!-- Generated by `agentgate docs metrics`. Do not edit by hand. -->
# Metric catalogue

Every metric implements one protocol and declares four things: its **family**, its **dtype**
(which decides what statistical machinery Part C allows for it), its **direction**, and its
**requirements**. A metric whose requirements a task does not satisfy is *skipped*, never scored
zero — scoring a missing reference as 0 would make a task-authoring gap look like an agent
regression.

"""


def _summary(metric: Metric) -> str:
    """One-line summary: the declared description, else the class docstring's first line."""
    described = getattr(metric, "description", "")
    if described:
        return " ".join(described.split())
    doc = inspect.getdoc(type(metric)) or ""
    return doc.splitlines()[0] if doc else ""


def _requirements(metric: Metric) -> str:
    if not metric.requires:
        return "—"
    return ", ".join(f"`{requirement.value}`" for requirement in sorted(metric.requires))


def render_metrics_doc() -> str:
    """Render the full metric catalogue as Markdown."""
    lines = [_HEADER]
    total = 0
    for family in MetricFamily:
        metrics = registry.by_family(family)
        lines.append(f"## {family.value}\n")
        intro = FAMILY_INTROS.get(family)
        if intro:
            lines.append(f"{intro}\n")
        if not metrics:
            lines.append("_No metrics registered in this family._\n")
            continue
        lines.append("| Metric | dtype | direction | requires | Definition |")
        lines.append("|---|---|---|---|---|")
        for metric in metrics:
            total += 1
            lines.append(
                f"| `{metric.name}` | {metric.dtype} | {metric.direction} | "
                f"{_requirements(metric)} | {_summary(metric)} |"
            )
        lines.append("")
    lines.append(f"---\n\n{total} metrics registered.\n")
    return "\n".join(lines)


def write_metrics_doc(path: str | Path = "docs/metrics.md") -> Path:
    """Write the metric catalogue to ``path``.

    Args:
        path: Destination file; parent directories are created.

    Returns:
        The path written.
    """
    target = Path(path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_metrics_doc(), encoding="utf-8")
    return target


def metrics_doc_is_current(path: str | Path = "docs/metrics.md") -> bool:
    """True when the committed catalogue matches the registry."""
    target = Path(path)
    return target.exists() and target.read_text(encoding="utf-8") == render_metrics_doc()
